name: pipeline 

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

jobs:
   build:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout del codigo
        uses: actions/checkout@v4
      - name: usar NODE JS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: contruir app con node
        run: npm install
      
