name: pipeline 

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: usar NODE JS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: construir app con node
        working-directory: ./CD_CI_MiPrimerAPI
        run: npm install

      - name: verificar si app.js existe
        run: |
          if [ ! -f "$GITHUB_WORKSPACE/CD_CI_MiPrimerAPI/app.js" ]; then
            echo "No se encontro app.js en la carpeta correcta."
            exit 1
          fi
          echo "Se encontro app.js. Continuando con el workflow"